### ISSUE TITLE
how are features_1res extracted from resnet? 

### ISSUE THREAD

**Issue by feiliu95** [fukun07/neural-image-captioning#11]
Dear author,
I have some confusion.
First, how are features_1res extracted from resnet? apply global pooling on the 'res5c' convolutional feature maps? 
Second, which ResNet network is used for the extraction of visual features? ResNet-101 or the others?
Thank you!

**Comment by fukun07** [comment]
Hi, we used ResNet-152, and treat the output of layer "pool5" as the feature.
