### ISSUE TITLE
A typo in readme.md

### ISSUE THREAD

**Issue by jamiechoi1995** [fukun07/neural-image-captioning#7]
Hello,

I found a typo in readme.md

> Introduction
> 
> This code is used in the paper "Aligning Where to See and What to Tell: Image Captioning with Region-based Attention and Scene-specific Contexts". See our arXiv version.
> 
> We provide detailed steps to reproduce the results reported in our paper. The two novel techniques are:
> 
> scene-specific contexts: text topics of images are **extraced** ......

I think **extraced** should be **extracted** here, thanks.

**Comment by fukun07** [comment]
Thanks! Having fixed it.
