### ISSUE TITLE
A code error or my mistake ? 

### ISSUE THREAD

**Issue by MenSanYan** [fukun07/neural-image-captioning#9]
/codes/model/ra.py
line 72:	self._feat_shared = theano.shared(np.zeros((1, npatch, nimg)).astype(theano.config.floatX))
line 105:   self._feat_shared.set_value(self._proj_func(img_value))
Because function '_proj_func' condenses the last dim of a tensor from 'nimg' to 'na'. 
So, should the shape of '_feat_shared' be (1, npatch, nimg) or (1, npatch, na) ?
Does an error exist in line 72 ?

**Comment by MenSanYan** [comment]
@fukun07 Anticipate your help. Thanks.

**Comment by fukun07** [comment]
Thanks, it's my mistake. The correct shape should be [1, npatch, na]. However, it should not influence the training and inference results, because the initial value of _shared_feat are over written by the image features when calling init_func(). I have fixed this in ra.py and rass.py.
